/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as EmprestimosRouteImport } from './routes/emprestimos'
import { Route as IndexRouteImport } from './routes/index'

const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimosRoute = EmprestimosRouteImport.update({
  id: '/emprestimos',
  path: '/emprestimos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emprestimos': typeof EmprestimosRoute
  '/livros': typeof LivrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emprestimos': typeof EmprestimosRoute
  '/livros': typeof LivrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emprestimos': typeof EmprestimosRoute
  '/livros': typeof LivrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/emprestimos' | '/livros'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/emprestimos' | '/livros'
  id: '__root__' | '/' | '/emprestimos' | '/livros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmprestimosRoute: typeof EmprestimosRoute
  LivrosRoute: typeof LivrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimos': {
      id: '/emprestimos'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof EmprestimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmprestimosRoute: EmprestimosRoute,
  LivrosRoute: LivrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
